### PR TITLE
fix: post results with nonzero exit code

### LINKED ISSUE #111: Runs with failed assertions don't get posted to comments
When a run has failed assertions, `promptfoo/actions` should post the output of that run as specified in the following image

Run with failed assertions

### PR DESCRIPTION
**Pull request by typpo**
Fixes #111

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -138,7 +138,16 @@ export async function run(): Promise<void> {
...
+    try {
+      await exec.exec(`npx promptfoo@${version}`, promptfooArgs, {env});
+    } catch (error) {
+      // Ignore nonzero exit code
+      if (error instanceof Error) {
+        core.info(`promptfoo exited with error: ${error.message}`);
+      } else {
+        core.info(`promptfoo exited with an unknown error.`);
+      }
+    }
```
Comment (nwaughachukwuma) [inline src/main.ts:150]: I think it's best to post the result of a failed run and still throw error (fail the CI job run)

Comment (nwaughachukwuma) [reply src/main.ts:150]: That way, we don't have a job run where there's a failed assertion and the CI passes.

Comment (nwaughachukwuma) [reply src/main.ts:150]: If it does not align with your philosophy is here, you should consider exposing a flag/option for this.
